source "https://rubygems.org"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
gem "github-pages", "~> 212", group: :jekyll_plugins
gem "webrick"

# If you have any plugins, put them here!
group :jekyll_plugins do
end
