name: build specs
on:
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  build-specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - name: Build specs
        run: |
          npm install
          npm run build:specs
