name: deploy website
on:
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Merge main into website
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: website
          github_token: ${{ github.token }}
      - name: Checkout website to _website folder
        uses: actions/checkout@v2
        with:
          ref: website
          path: ./_website
          clean: false
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      - name: Deploy website
        run: |
          cd ./_website
          npm install
          npm run build:website
          rm -rdvf ./docs
          mv ./.vuepress/dist ./docs
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m 'deploy website'
          git push -f
